In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('classFile.csv', sep='\t', usecols=['num','filename','totalTables','wellFormedTables','notWellFormedTables',
                                                   'tocTables','infoboxTables','smallDimTables','otherTables',
                                                   'usefulTables','withInnerTables','wikiTables','tracklistTables','otherUsefulTables'])

In [3]:
df.head()

,num,filename,totalTables,wellFormedTables,notWellFormedTables,tocTables,infoboxTables,smallDimTables,otherTables,usefulTables,withInnerTables,wikiTables,tracklistTables,otherUsefulTables
0,0,Mario Sandoval.html.bz2,2,2,0,0,1,0,1,0,0,0,0,{}
1,2,Raydell Kewal.html.bz2,1,1,0,0,0,0,1,0,0,0,0,{}
2,1,Ichibu Station (Nara).html.bz2,5,5,0,0,1,0,3,1,0,1,0,{}
3,3,Ron White (footballer).html.bz2,2,2,0,0,1,0,1,0,0,0,0,{}
4,4,Ramakrishna Badiga.html.bz2,3,3,0,0,1,0,2,0,0,0,0,{}

In [4]:
df.describe()

,num,totalTables,wellFormedTables,notWellFormedTables,tocTables,infoboxTables,smallDimTables,otherTables,usefulTables,withInnerTables,wikiTables,tracklistTables
count,5.582847e+06,5.582847e+06,5.582847e+06,5.582847e+06,5.582847e+06,5.582847e+06,5.582847e+06,5.582847e+06,5.582847e+06,5.582847e+06,5.582847e+06,5.582847e+06
mean,2.791651e+06,3.329689e+00,3.328775e+00,9.142289e-04,1.866736e-02,6.876463e-01,6.329495e-02,1.821861e+00,7.373057e-01,2.020922e-02,4.615804e-01,2.298254e-02
std,1.611762e+06,6.633115e+00,6.631247e+00,4.714617e-02,2.021857e-01,7.174051e-01,1.201150e+00,3.456999e+00,4.264549e+00,4.516006e-01,2.518452e+00,2.710877e-01
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.395826e+06,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.791653e+06,3.000000e+00,3.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,4.187484e+06,4.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,5.583302e+06,1.081000e+03,1.081000e+03,3.100000e+01,6.500000e+01,2.070000e+02,9.870000e+02,8.830000e+02,6.760000e+02,2.040000e+02,6.440000e+02,7.000000e+01

In [6]:
sum(df['totalTables'])

18589145

In [8]:
print('wellFormedTables = ',sum(df['wellFormedTables']))
print('notWellFormedTables = ',sum(df['notWellFormedTables']))
print ('tocTables = ',sum(df['tocTables']))
print ('infoboxTables = ',sum(df['infoboxTables']))
print ('otherTables = ',sum(df['otherTables']))
print ('smallDimTables = ',sum(df['smallDimTables']))
print ('usefulTables = ',sum(df['usefulTables']))
print ('wikiTables = ',sum(df['wikiTables']))
print ('tracklistTables = ',sum(df['tracklistTables']))

print ('withInnerTables = ',sum(df['withInnerTables']))

wellFormedTables =  18584041
notWellFormedTables =  5104
tocTables =  104217
infoboxTables =  3839024
otherTables =  10171169
smallDimTables =  353366
usefulTables =  4116265
wikiTables =  2576933
tracklistTables =  128308
withInnerTables =  112825

In [9]:
len(df.filename.unique())

5582847

In [10]:
dfu=df[df['usefulTables']>=1]

In [11]:
dfu.describe()

,num,totalTables,wellFormedTables,notWellFormedTables,tocTables,infoboxTables,smallDimTables,otherTables,usefulTables,withInnerTables,wikiTables,tracklistTables
count,1.121235e+06,1.121235e+06,1.121235e+06,1.121235e+06,1.121235e+06,1.121235e+06,1.121235e+06,1.121235e+06,1.121235e+06,1.121235e+06,1.121235e+06,1.121235e+06
mean,2.794293e+06,7.122623e+00,7.119648e+00,2.975291e-03,4.358587e-02,8.825723e-01,2.310443e-01,2.291257e+00,3.671188e+00,1.006256e-01,2.298299e+00,1.144345e-01
std,1.611830e+06,1.379219e+01,1.378862e+01,9.362376e-02,2.964635e-01,1.091733e+00,2.564188e+00,7.182888e+00,8.932117e+00,1.003684e+00,5.230653e+00,5.961952e-01
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.399263e+06,3.000000e+00,3.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00
50%,2.794847e+06,5.000000e+00,5.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,2.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00
75%,4.189589e+06,7.000000e+00,7.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,3.000000e+00,3.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00
max,5.583289e+06,1.081000e+03,1.081000e+03,3.100000e+01,6.500000e+01,2.070000e+02,9.870000e+02,8.830000e+02,6.760000e+02,2.040000e+02,6.440000e+02,7.000000e+01

In [12]:
res=dfu['filename'].sort_values()

In [30]:
res.to_csv('archivosUseful', sep="\t", index=False)